apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.appConfig.server.port | default 8080 }}
      targetPort: {{ .Values.appConfig.server.port | default 8080 }}
      protocol: TCP

    {{- if .Values.appConfig.grpc.server }}
    - name: grpc
      port: {{ .Values.appConfig.grpc.server.port | default 9090 }}
      targetPort: {{ .Values.appConfig.grpc.server.port | default 9090 }}
      protocol: TCP
    {{- end }}
  selector:
    app: {{ .Release.Name }}
